package logic;

public enum EventType {
    ON_DUTY,
    OFF_DUTY,
    SLEEP,
    DRIVING,
    LOGIN,
    LOGOUT,
    INTERMEDIATE_EVENT,
    POWER_UP,
    POWER_DOWN,
    MALFUNCTION_LOGGED,
    MALFUNCTION_CLEARED,
    DATA_DIAGNOSTIC_LOGGED,
    DATA_DIAGNOSTIC_CLEARED,
    PERSONAL_USE,
    YARD_MOVE,
    PC_CLEARED,
    CERTIFICATION
}
